version: '3.8'

services:
  allure-landing:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: allure-landing-app
    ports:
      - "4000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=${DOMAIN:-ws-allure.com}
      - VIRTUAL_PORT=5173
    networks:
      - allure-network

networks:
  allure-network:
    driver: bridge
